### ISSUE TITLE
i9 9980xe

### ISSUE THREAD

**Issue by zcwaa22** [yifan-gu/hackintosh#1]
Hi, 

Ive been using your EFI and Bios settings to run Catalina on my machine:

i9 9980XE
Asus Prime X299 II
64gb Ram 
Vega 64
Broadcom Mini PCI Wifi/Bluetooth ( Worked OOTB in Mojave)

All works fine except bluetooth and am getting super low benchmarks in Geekbench- ~14000 multicore ( I think under Mojave I was getting ~64000)

If you could point me in the right direction to fixing these it would be much appreciated :)

**Comment by gaozzb** [comment]
I have this problem too

**Comment by gaozzb** [comment]
I don't kown to doing?

**Comment by yifan-gu** [comment]
Hi you might want to use https://github.com/yifan-gu/hackintosh/blob/master/stress_cpu.sh to check if all the cores are running.
But it's from long time ago I can't remember the details, sorry.
