### ISSUE TITLE
不太会用，这东西有点高级呀

### ISSUE THREAD

**Issue by gaozzb** [yifan-gu/hackintosh#4]
我不太看得懂你的思路，我把EFI的两个压缩文件都解压试了，提示这个

![133a73a149d5c2f9276c8ce7f6d7a09](https://user-images.githubusercontent.com/49707040/100495939-148e0900-318b-11eb-8ff2-77713bf23373.jpg)

**Comment by yifan-gu** [comment]
Hi, you might need to update UUID. but it's too long ago I can't remember the details now
